name: Deploy via SSH (No Runner Needed)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}           # Use secret for server IP
          username: ${{ secrets.SERVER_USER }}     # Use secret for SSH username
          key: ${{ secrets.SERVER_SSH_KEY }}       # Use secret for SSH private key
          port: 22
          script: |
            cd /home/nodeapp
            git pull origin main
            sudo systemctl restart nginx
            pm2 start server.js 

