name: Deploy App Using SSH Key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        # Save the SSH private key to a file
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/gitkey.pem
        chmod 600 ~/.ssh/gitkey.pem

        # Create ~/.ssh directory if not already present
        mkdir -p ~/.ssh

        # Add the server's SSH key to known_hosts to avoid prompts on first connection
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to Server using SSH
      run: |
        # Use the private key and SSH into the server
        ssh -i ~/.ssh/gitkey.pem -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          # Navigate to the project directory
          cd /home/nodeapp || exit 1

          # Git operations
          echo "--- Git Info ---"
          git config --global --add safe.directory /home/nodeapp
          git fetch origin
          git checkout main
          git reset --hard origin/main

          # Install dependencies
          echo "--- Installing dependencies ---"
          npm install

          # Restart PM2 or start the server if not running
          echo "--- Restarting PM2 ---"
          pm2 restart server || pm2 start /home/nodeapp/server.js --name server

          echo "✅ Deployment Complete"
        EOF

         
