
name: Deploy App Using SSH Key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
  
    - name: Deploy to Server using SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/nodeapp
          git pull origin main
          pm2 restart app || pm2 start app.js --name app
        EOF
