
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass openssh-client

    - name: Add SSH private key to ssh-agent
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        
    - name: Deploy to Server using SSH with SSH key
      run: |
       ssh -t -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
       cd /home/nodeapp || exit 1
       sudo chown -R nodeapp:nodeapp /home/nodeapp
       sudo -u nodeapp git fetch origin
       sudo -u nodeapp git reset --hard origin/main
       pm2 restart server || pm2 start /home/***/server.js --name server
       EOF


    
