on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Connect and pull latest code
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd ${{ secrets.WORK_DIR }} || exit 1
          sudo -u root git fetch origin
          sudo -u root git reset --hard origin/${{ secrets.MAIN_BRANCH }}
          pm2 restart server || pm2 start server.js --name server
        EOF

    - name: Cleanup SSH
      run: rm -rf ~/.ssh
