on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass
      
     
    - name: Deploy to Server using SSH with password
      run: |
        sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/nodeapp || exit 1
          sudo chown -R nodeapp:nodeapp /home/nodeapp
          sudo -u nodeapp git fetch origin
          sudo -u nodeapp git reset --hard origin/main
          pm2 restart server || pm2 start server.js --name app
        EOF
