on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH for GitHub Actions
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /nodeapp/.ssh/id_rsa
        chmod 600 /nodeapp/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> /nodeapp/.ssh/known_hosts

    - name: Deploy to server via SSH
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/nodeapp || exit 1
          sudo chown -R nodeapp:nodeapp /home/nodeapp
          sudo -u nodeapp git fetch origin
          sudo -u nodeapp git reset --hard origin/main
          pm2 restart server || pm2 start /home/nodeapp/server.js --name server
        EOF
