on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH for GitHub Actions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to server via SSH
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          # Debugging info
          echo "Current user: $(whoami)"
          echo "PM2 version: $(pm2 -v)"
          echo "PM2 status:"
          pm2 status

          # Change to the application directory
          cd /home/nodeapp || exit 1
          
          # Pull the latest code from the main branch
          git pull origin main

          # Set ownership of the application files to the 'nodeapp' user
          sudo chown -R nodeapp:nodeapp /home/nodeapp

          # Fetch latest changes and reset to 'main' branch
          sudo -u nodeapp git fetch origin
          sudo -u nodeapp git reset --hard origin/main

          # Ensure PM2 is available in the current PATH
          export PATH=$PATH:/usr/local/bin

          # Restart PM2 process or start it if not already running
          sudo -u nodeapp pm2 status || pm2 start /home/***/server.js --name server
          sudo -u nodeapp pm2 restart server || pm2 start /home/***/server.js --name server
        EOF



