on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH for GitHub Actions
      run: |
        mkdir -p /home/nodeapp/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/nodeapp/.ssh/id_rsa
        chmod 600 /home/nodeapp/.ssh/id_rsa

    - name: Deploy to server via SSH
      run: |
        ssh -i /nodeapp/home/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/nodeapp || exit 1
          sudo chown -R nodeapp:nodeapp /home/nodeapp
          sudo -u nodeapp git fetch origin
          sudo -u nodeapp git reset --hard origin/main
          pm2 restart server || pm2 start /home/***/server.js --name server
        EOF

