name: Deploy App Using SSH Key

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > gitkey.pem
        chmod 600 gitkey.pem
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
    - name: Deploy to Server using SSH
      run: |
        ssh -i gitkey.pem -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/jobin/test || exit 1
          echo "--- Git Info ---"
          git config --global --add safe.directory /home/jobin/test
          git fetch origin
          git checkout main
          git reset --hard origin/main
          echo "--- Installing dependencies ---"
          npm install
          echo "--- Restarting PM2 ---"
          pm2 restart app || pm2 start app.js --name app
          echo "✅ Deployment Complete"
          EOF
