on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH for GitHub Actions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy to server via SSH
      run: |
        # Connect to the remote server and deploy the code
        ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          # Navigate to the application directory
          cd /home/nodeapp || exit 1
          
          # Ensure the ownership is set correctly
          sudo chown -R nodeapp:nodeapp /home/nodeapp

          # Fetch the latest code from the main branch
          sudo -u nodeapp git fetch origin
          sudo -u nodeapp git reset --hard origin/main

          # Ensure pm2 is installed (this might be redundant if already installed)
          if ! command -v pm2 &> /dev/null
          then
            echo "pm2 could not be found, installing it..."
            sudo npm install -g pm2
          fi

          # Restart the server with pm2 or start if not running
          if pm2 status server | grep -q "online"; then
            pm2 restart server;
          else
            pm2 start /home/nodeapp/server.js --name server;
          fi
        EOF

